name: Publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps and build
        run: npm ci && npm run build
      - name: Push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "feat: add dist"
          git push
